version: '3'
services:
    config-service:
        image: springcloudmoduletest-configservice:1.0.0
        restart: unless-stopped
        ports:
            - "8888:8888"
        networks:
            - cloudTestNetwork
    registry-service:
        image: springcloudmoduletest-registryservice:1.0.0
        restart: unless-stopped
        ports:
            - "8761:8761"
        networks:
            - cloudTestNetwork
        depends_on:
            - config-service
    gateway-service:
        image: springcloudmoduletest-gatewayservice:1.0.0
        restart: unless-stopped
        ports:
            - "80:8080"
        networks:
            - cloudTestNetwork
        depends_on:
            - registry-service
            - config-service

    author-service:
        image: springcloudmoduletest-authorservice:1.0.0
        restart: unless-stopped
        networks:
            - cloudTestNetwork
        depends_on:
            - gateway-service
    article-service:
        image: springcloudmoduletest-articleservice:1.0.0
        networks:
            - cloudTestNetwork
        depends_on:
            - gateway-service

    database-postgres:
        image: postgres:15
        restart: unless-stopped
        environment:
            - POSTGRES_DB=testCloudApplication
            - POSTGRES_USER=haart
            - POSTGRES_PASSWORD=phaart
        ports:
            - '5432:5432'
        networks:
            - cloudTestNetwork
    pgadmin:
        image: dpage/pgadmin4:latest
        restart: unless-stopped
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
            - '15432:80'
        networks:
            - cloudTestNetwork

    product-producer:
        image: springcloudmoduletest-productproducer:1.0.0
        restart: unless-stopped
        networks:
            - cloudTestNetwork
        depends_on:
            - gateway-service
    product-database-consumer:
        image: springcloudmoduletest-productdatabaseconsumer:1.0.0
        restart: unless-stopped
        networks:
            - cloudTestNetwork
        depends_on:
            - gateway-service
            - database-postgres
    product-console-consumer:
        image: springcloudmoduletest-productconsoleconsumer:1.0.0
        restart: unless-stopped
        networks:
            - cloudTestNetwork
        depends_on:
            - gateway-service

    zookeeper:
        image: confluentinc/cp-zookeeper:6.2.0
        restart: unless-stopped
        networks:
            - cloudTestNetwork
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
    kafka:
        image: confluentinc/cp-kafka:7.0.0
        restart: unless-stopped
        networks:
            - cloudTestNetwork
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#    kafka-manager:
#        image: hlebalbau/kafka-manager:stable
#        restart: unless-stopped
#        ports:
#            - "9000:9000"
#        environment:
#            - ZK_HOSTS=zookeeper:2181
#        networks:
#            - cloudTestNetwork
#        depends_on:
#            - zookeeper
    kafka-ui:
        container_name: kafka-ui
        image: provectuslabs/kafka-ui:latest
        restart: unless-stopped
        ports:
            - "8080:8080"
        environment:
            DYNAMIC_CONFIG_ENABLED: true
        networks:
            - cloudTestNetwork
        depends_on:
            - zookeeper

    geocoder-service:
        image: springcloudmoduletest-geocoderservice:1.0.0
        restart: unless-stopped
        networks:
            - cloudTestNetwork
        depends_on:
            - gateway-service

networks:
    cloudTestNetwork:
        driver: bridge
