version: '3'
services:
    config-service:
        build: ./ConfigService
        ports:
            - "8888:8888"
        networks:
            - cloudTestNetwork

    registry-service:
        build: ./RegistryService
        ports:
            - "8761:8761"
        networks:
            - cloudTestNetwork
        depends_on:
            - config-service

    gateway-service:
        build: ./GatewayService
        ports:
            - "8080:8080"
        networks:
            - cloudTestNetwork
        depends_on:
            - registry-service

    author-service:
        build: ./AuthorService
        networks:
            - cloudTestNetwork
        depends_on:
            - gateway-service

    article-service:
        build: ./ArticleService
        networks:
            - cloudTestNetwork
        depends_on:
            - gateway-service

networks:
    cloudTestNetwork:
        driver: bridge
