spring:
    application:
        name: ServiceDiscovery
server:
    port: 8761
eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        instance-id: ${spring.application.name}:${random.value}
