spring:
    application:
        name: ServiceDiscovery
server:
    port: 9002
eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://localhost:9002/eureka/
