spring:
    application:
        name: ProductConsoleConsumer
    datasource:
        url: jdbc:h2:mem:mydb
        username: sa
        password: password
        driverClassName: org.h2.Driver
    jpa:
        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    kafka:
        consumer:
            bootstrap-servers: kafka:29092
            group-id: product-console-consumer
application:
    kafka:
        topic: product-topic
