spring:
    application:
        name: GeocoderService
    redis:
        host: redis
        port: 6379
    datasource:
        url: jdbc:postgresql://database-postgres:5432/testCloudApplication
        username: haart
        password: phaart
        driverClassName: org.postgresql.Driver
    jpa:
        spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
        hibernate:
            ddl-auto: update
