spring:
    application:
        name: ProductDatabaseConsumer
    datasource:
        url: jdbc:postgresql://database-postgres:5432/testCloudApplication
        username: haart
        password: phaart
        driverClassName: org.postgresql.Driver
    jpa:
        spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
        hibernate:
            ddl-auto: update
    kafka:
        consumer:
            bootstrap-servers: kafka:29092
            group-id: product-database-consumer
application:
    kafka:
        topic: product-topic
