name: Java CI with Maven

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Git clone
              uses: actions/checkout@v3

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'

            - name: Set up Maven
              uses: actions/setup-java@v2
              with:
                  java-version: '17'
                  distribution: 'adopt'
                  server-id: central
                  settings-path: ${{ github.workspace }}/settings.xml

            - name: Build with Maven
              run: ./mvnw clean install
